name: WooWoo
options:
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
targets:
  WooWoo:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.woowoothegame
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Sources/App/Info.plist
        SWIFT_VERSION: "6.0"
        CODE_SIGN_STYLE: Automatic
        SUPPORTED_INTERFACE_ORIENTATIONS: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
  WooWooTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: WooWoo
schemes:
  WooWoo:
    build:
      targets:
        WooWoo: all
    test:
      targets: [WooWooTests]
